name: OpenTofu Azure Storage Setup

on:
  push:
    branches:
      - '**'

jobs:
  opentofu:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh && \
          chmod +x install-opentofu.sh && \
          ./install-opentofu.sh --install-method deb && \
          rm -f install-opentofu.sh
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Change to infrastructure directory
        run: cd infrastructure/

      - name: Run OpenTofu commands
        run: |
          tofu init
          tofu plan
          tofu apply -auto-approve
