name: OpenTofu Azure Storage Setup

on:
  push:
    branches:
      - '**'

jobs:
  opentofu:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          curl -s https://install.opentofu.org | bash
          echo "$HOME/.opentofu/bin" >> $GITHUB_PATH

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run OpenTofu commands
        run: |
          tofu init
          tofu plan
          tofu apply -auto-approve
