name: OpenTofu Azure Storage Setup

on:
  push:
    branches:
      - '**'
      
jobs:
  opentofu:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh && \
          chmod +x install-opentofu.sh && \
          ./install-opentofu.sh --install-method deb && \
          rm -f install-opentofu.sh

      - name: Run OpenTofu commands
        run: |
          tofu init && \
          tofu plan && \
          tofu apply -auto-approve
