name: OpenTofu Azure Storage Setup

on:
  push:
    branches:
      - '**'

jobs:
  opentofu:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenTofu
        run: |
          curl -s https://install.opentofu.org | bash
          echo "$HOME/.opentofu/bin" >> $GITHUB_PATH

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Run OpenTofu commands
        run: |
          tofu init
          tofu plan
          tofu apply -auto-approve
